openapi: 3.0.0
info:
  title: Pets
  description: Collection to test path parameters
  version: 1.0.0
servers:
  - url: http://{{base_usl}}{{api}}
paths:
  /pet/info/countries/{counties}/language/{language}:
    post:
      tags:
        - General
      summary: Create a pet infomation
      description: create infomation of pet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: []
              example:
                pet: dog
                info:
                  name: pizza
                  age: 1.2
                  behavior:
                    - freindly
                owner:
                  - name: santa
                    age: 30
                    address:
                      address_1: 174 wo wo town
                      city: dao namex
                      country: wakanda
                alive: true
              properties:
                pet:
                  description: |-
                    pet type 

                     Example: dog
                  type: string
                  enum:
                    - dog
                    - cat
                    - bird
                  minimum: '1'
                  maximum: '10'
                info:
                  type: object
                  allOf:
                    - required:
                        - name
                      properties:
                        name:
                          description: |-
                            name of pet 

                             Example: pizza
                          type: string
                          pattern: ' regex = "\[a-z\]"'
                        age:
                          type: float
                          title: title_example
                        behavior:
                          type: Array of strings
                          items:
                            required: []
                            properties: {}
                owner:
                  type: array
                  items:
                    required: []
                    properties:
                      name:
                        type: string
                      age:
                        type: integer
                      address:
                        type: object
                        allOf:
                          - required: []
                            properties: {}
                alive:
                  type: boolean
      parameters:
        - name: counties
          in: path
          schema:
            type: string
            default: tha
            enum:
              - tha
              - eng
            minimum: '10'
            maximum: '100'
          required: true
          description: params
          example: cba
        - name: language
          in: path
          schema:
            type: string
            default: thai
            enum:
              - thai
              - english
            minimum: '1'
            maximum: '10'
          required: true
          description: hello params
          example: abc
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: Content-Type
          content:
            application/json:
              schema:
                type: object
                required: []
                example:
                  example:
                    meta:
                      code: '201'
                      type: Create
                      message: The request was successfully processed.
                      error:
                        - path: ''
                          info: ''
                    data:
                      id: string
                      pet: dog
                      info:
                        name: pizza
                        age: 1.2
                        behavior:
                          - freindly
                      owner:
                        - name: santa
                          age: 30
                          address:
                            address_1: 174 wo wo town
                            city: dao namex
                            country: wakanda
                      alive: true
                      created_at: '2022-02-12T04:30:30.359Z'
                properties:
                  meta:
                    type: object
                    allOf:
                      - required: []
                        properties:
                          code:
                            type: string
                          type:
                            type: string
                  data:
                    type: object
                    allOf:
                      - required: []
                        properties:
                          id:
                            type: string
                          pet:
                            type: string
                          info:
                            type: object
                            allOf:
                              - required: []
                                properties:
                                  name:
                                    type: string
                                  age:
                                    type: float
                                  behavior:
                                    type: Array of strings
                                    items:
                                      required: []
                                      properties: {}
                          owner:
                            type: array
                            items:
                              required: []
                              properties:
                                name:
                                  type: string
                                age:
                                  type: integer
                                address:
                                  type: object
                                  allOf:
                                    - required: []
                                      properties:
                                        address_1:
                                          type: string
                                        city:
                                          type: string
                                        country:
                                          type: string
                          alive:
                            type: boolean
                          created_at:
                            type: string
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: Content-Type
          content:
            application/json:
              schema:
                type: object
                required: []
                example:
                  example:
                    meta:
                      code: '400'
                      type: Bad Request
                      message: The request was error processed.
                      error:
                        - path: ''
                          info: ''
                    data: {}
                properties:
                  meta:
                    type: object
                    allOf:
                      - required: []
                        properties:
                          code:
                            description: |
                              error 400 
                            type: string
                          type:
                            type: string
                  data:
                    type: object
                    allOf:
                      - required: []
                        properties: {}
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: Content-Type
          content:
            application/json:
              schema:
                type: object
                required: []
                example:
                  example:
                    meta:
                      code: '500'
                      type: Internal Server Error
                      message: The request was error processed.
                      error:
                        - path: ''
                          info: ''
                    data: {}
                properties:
                  meta:
                    type: object
                    allOf:
                      - required: []
                        properties:
                          code:
                            description: |
                              error 500 
                            type: string
                          type:
                            type: string
                  data:
                    type: object
                    allOf:
                      - required: []
                        properties: {}
